### PR TITLE
Refactored timezones tests and slightly changed timezone portion of w…

### PR DESCRIPTION
**Pull request by jrauschenberg**
#### What's this PR do?
Final third version of timezones tests. Production code is intact with very slight changes. Tests are refactored to use WiW mocker and passing.
#### Where should the reviewer start?
test/timezone.js and www/scheduling/index.js (the timezone portion of the code)
#### How should this be manually tested?
"npm test" or manually with node.
#### What are the relevant tickets?
No current tickets. Refactor of old, closed ticket.
#### Questions:

…ww/scheduling/index.js.

### CODE REVIEW

**Comment by tongxiang** [comment]
Please make sure to test your code before submitting a PR. Running this threw an error, because of how we refactored module.exports: 

```
/Users/tongxiang/ctl/Elmer/node_modules/express/lib/router/index.js:327
    throw new Error(msg);
    ^

Error: Router.use() requires callback functions but got a [object Object]
    at Function.proto.use (/Users/tongxiang/ctl/Elmer/node_modules/express/lib/router/index.js:327:11)
    at Function.app.use (/Users/tongxiang/ctl/Elmer/node_modules/express/lib/application.js:195:16)
    at Object.<anonymous> (/Users/tongxiang/ctl/Elmer/www/app.js:33:5)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

**Comment by jrauschenberg** [comment]
I always test first! Again no idea how this got in. But I'm on it.

**Comment by jrauschenberg** [comment]
Should be fixed and ready to merge now. Let me know. Sorry!

**Comment by tongxiang** [comment]
👍

**Pull request merged**
